# Introduction to NumPy 🔥

Shamelessly taken from
https://docs.scipy.org/doc/numpy/user/quickstart.html

## Importing NumPy
Convention is to import NumPy the following way:

In [1]:
import numpy as np

## Basics


NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), **all of the same type**, indexed by a tuple of positive integers. In NumPy dimensions are called axes.

For example, the coordinates of a point in 3D space `[1, 2, 1]` has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.  
```python
[[ 1., 0., 0.],
 [ 0., 1., 2.]]
```

NumPy’s array class is called `ndarray` (usually just called array).

## Array Creation

There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the `array` function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [2]:
a = np.array([2,3,4])
a

array([2, 3, 4])

Keep in mind this array is created by passing a list to `array`, not by passing individual numbers!

`array` transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [3]:
b = np.array(
    [
        (1, 2, 3),
        (4, 5, 6)
    ]
)
b

array([[1, 2, 3],
       [4, 5, 6]])

The type of the array can also be explicitly specified at creation time:

In [4]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Often, the elements of an array are originally unknown, but its shape is known. Hence, NumPy offers several functions to create arrays with set shape and initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function `zeros` creates an array full of zeros, the function `ones` creates an array full of ones, and the function `empty` creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is `float64` (i.e. a float with 64 bits precision).

To create an array like this, you

In [5]:
np.zeros((3,4)) # Instead of values, pass a shape, in this case we want a 3x4 matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,3,4), dtype=np.int16)   # data type can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists:

In [8]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

## Array properties
The more important attributes of an ndarray object are:

- `ndim:` the number of axes (dimensions) of the array.

In [9]:
a = np.array(
    [
        [1, 3, 4],
        [6, 1, 8]
    ]
)

a.ndim

2

- `shape:` the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with $n$ rows and $m$ columns, shape will be `(n,m)`. The length of the shape tuple is therefore the number of axes, `ndim`.

In [10]:
a.shape

(2, 3)

- `size:` the total number of elements of the array. This is equal to the product of the elements of `shape`.

In [11]:
a.size

6

- `dtype:` an object describing the type of the elements in the array. NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

In [12]:
a.dtype

dtype('int32')

## Basic Operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [13]:
a = np.array([20,30,40,50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [14]:
a - b

array([20, 29, 38, 47])

In [15]:
a + 5

array([25, 35, 45, 55])

In [16]:
10 * a

array([200, 300, 400, 500])

In [17]:
b ** 2

array([0, 1, 4, 9], dtype=int32)

In [18]:
a < 35

array([ True,  True, False, False])

Unlike in many matrix languages, the product operator `*` operates elementwise in NumPy arrays. The matrix product can be performed using the `dot` function:

In [19]:
A = np.array(
    [[1,1],
     [0,1]]
)
B = np.array(
    [[2,0],
     [3,4]]
)

In [20]:
A * B # Elementwise product

array([[2, 0],
       [0, 4]])

In [21]:
A @ B # Matrix product

array([[5, 4],
       [3, 4]])

In [22]:
A.dot(B) # Also matrix product

array([[5, 4],
       [3, 4]])

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [23]:
a = np.random.random((2,3)) # Create a random array
a

array([[0.42956108, 0.02747901, 0.20590671],
       [0.26250716, 0.0869213 , 0.23579857]])

In [24]:
a.sum()

1.2481738212645017

In [25]:
a.min()

0.02747900602506992

In [26]:
a.max()

0.42956108110868685

## Indexing, Slicing, Iterating

**One-dimensional** arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [27]:
a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [28]:
a[2]

4

In [29]:
a[2:5]

array([ 4,  9, 16], dtype=int32)

In [30]:
a[:6:2] = -10

In [31]:
a

array([-10,   1, -10,   9, -10,  25,  36,  49,  64,  81], dtype=int32)

You can also slice by passing a list of indices!

In [32]:
a[[2, 4, 2]]

array([-10, -10, -10], dtype=int32)

In [33]:
for i in a:
    print(i + 3)

-7
4
-7
12
-7
28
39
52
67
84


**Multidimensional arrays** can have one index per axis. These indices are given in a tuple separated by commas:

In [34]:
b = np.arange(16).reshape((4, 4)) # More on reshaping later
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
b[2, 3]

11

In [36]:
b[0:5, 1] # each row in the second column of b

array([ 1,  5,  9, 13])

In [37]:
b[:, 1] # equivalent to the previous example

array([ 1,  5,  9, 13])

In [38]:
b[1:3, :] # each column in the second and third row of b

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Iterating over multidimensional arrays is done with respect to the first axis:

In [39]:
for row in b:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


However, if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array:

In [40]:
for element in b.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


## Shape Manipulation

The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:

In [41]:
b.ravel() # Returns the array, flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
b.reshape((2, 8)) # Returns the array with modified shape

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [43]:
b.T # Transpose

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

In [44]:
b.reshape((2, -1))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

## Stacking arrays

Several arrays can be stacked together along different axes:

In [45]:
a = np.random.random((2, 2)).round(2)
b = np.random.random((2, 2)).round(2)

In [46]:
np.vstack((a, b))

array([[0.35, 0.74],
       [0.66, 0.82],
       [0.51, 0.42],
       [0.1 , 0.74]])

In [47]:
np.hstack((a, b))

array([[0.35, 0.74, 0.51, 0.42],
       [0.66, 0.82, 0.1 , 0.74]])

In [48]:
np.hstack(
    (
        a,
        np.zeros((2, 3)),
        b
    )
)

array([[0.35, 0.74, 0.  , 0.  , 0.  , 0.51, 0.42],
       [0.66, 0.82, 0.  , 0.  , 0.  , 0.1 , 0.74]])